import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import {TooltipProvider} from "@/components/ui/tooltip";
import {Suspense} from "react";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={poppins.variable} suppressHydrationWarning>
      <body className="font-poppins" suppressHydrationWarning>
      <TooltipProvider>
        <Suspense fallback={null}>{children}</Suspense>
      </TooltipProvider>
      </body>
    </html>
  );
}
